# Usa l'immagine base
FROM forry2/nifi:1.24.0.2

# Copia il file quartorarieCsvGenerator.jar nella directory /tmp
COPY quartorarieCsvGenerator.jar /tmp/

LABEL maintainer="Roberto Bruni (roberto.bruni@dxc.com)"
LABEL description="This Docker image extends forry2/nifi:1.24.0.2 and includes the file quartorarieCsvGenerator.jar in the /tmp directory."